name: Bug Report
description: File a report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What is currently happening?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should be happening?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How do we trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
